import { useEffect, useState } from "react";
import axios from "axios";
import "../../styles/admin/GeneratedWorkouts.css";
import GeneratedWorkoutView from "../../components/GeneratedWorkoutView";
import ConfirmModal from "../../components/ConfirmModal";

const API_BASE = "/api";

export default function GeneratedWorkouts() {
  const [workouts, setWorkouts] = useState([]);
  const [loading, setLoading] = useState(false);

  const [viewOpen, setViewOpen] = useState(false);
  const [selected, setSelected] = useState(null);

  const [confirmOpen, setConfirmOpen] = useState(false);
  const [toDelete, setToDelete] = useState(null);

  const [dateErrorOpen, setDateErrorOpen] = useState(false);

  const [search, setSearch] = useState("");
  const [goal, setGoal] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  // Load workouts w/ filters
  const load = async () => {
    setLoading(true);

    try {
      const params = new URLSearchParams();
      params.append("page", page);
      params.append("limit", 10);

      if (search) params.append("search", search);
      if (goal) params.append("goal", goal);
      if (dateFrom) params.append("from", dateFrom);
      if (dateTo) params.append("to", dateTo);

      const res = await axios.get(
        `${API_BASE}/index.php?route=admin&action=getGeneratedWorkouts&${params.toString()}`
      );

      if (res.data.success) {
        setWorkouts(res.data.workouts);
        setTotalPages(res.data.pagination.totalPages);
      }
    } catch (err) {
      console.error(err);
    }

    setLoading(false);
  };

  useEffect(() => {
    load();
  }, [page]);

  useEffect(() => {
    setPage(1);
  }, [search, goal, dateFrom, dateTo]);

  const applyDateFilter = () => {
    if (dateFrom && dateTo && dateFrom > dateTo) {
      setDateErrorOpen(true);
      return;
    }
    load();
  };

  const resetFilters = () => {
    setSearch("");
    setGoal("");
    setDateFrom("");
    setDateTo("");
    load();
  };

  const openView = async (id) => {
    try {
      const res = await axios.get(
        `${API_BASE}/index.php?route=admin&action=getGeneratedWorkoutById&id=${id}`
      );
      if (res.data.success) {
        setSelected(res.data.workout);
        setViewOpen(true);
      }
    } catch (err) {
      console.error(err);
    }
  };

  const confirmDelete = (id) => {
    setToDelete(id);
    setConfirmOpen(true);
  };

  const doDelete = async () => {
    try {
      await axios.delete(
        `${API_BASE}/index.php?route=admin&action=deleteGeneratedWorkout&id=${toDelete}`
      );
      setConfirmOpen(false);
      setToDelete(null);
      load();
    } catch (err) {
      console.error(err);
    }
  };

  const renderPagination = () => {
    if (totalPages <= 1) return null;

    const pages = [];
    const maxVisible = 3;

    const addPage = (p) =>
      pages.push(
        <button
          key={p}
          className={`pg-btn ${page === p ? "active" : ""}`}
          onClick={() => setPage(p)}
        >
          {p}
        </button>
      );

    addPage(1);

    if (page > maxVisible + 2)
      pages.push(<span key="start" className="pg-ellipsis">…</span>);

    for (let p = page - maxVisible; p <= page + maxVisible; p++) {
      if (p > 1 && p < totalPages) addPage(p);
    }

    if (page < totalPages - (maxVisible + 1))
      pages.push(<span key="end" className="pg-ellipsis">…</span>);

    if (totalPages > 1) addPage(totalPages);

    return (
      <div className="pagination">
        <button
          className="pg-btn"
          disabled={page === 1}
          onClick={() => setPage(1)}
        >
          « First
        </button>

        <button
          className="pg-btn"
          disabled={page === 1}
          onClick={() => setPage(page - 1)}
        >
          ‹ Prev
        </button>

        {pages}

        <button
          className="pg-btn"
          disabled={page === totalPages}
          onClick={() => setPage(page + 1)}
        >
          Next ›
        </button>

        <button
          className="pg-btn"
          disabled={page === totalPages}
          onClick={() => setPage(totalPages)}
        >
          Last »
        </button>
      </div>
    );
  };

  return (
    <div className="admin-page generated-workouts-page">
      <h2>Generated Workouts</h2>
      <p className="subtitle">All workouts generated by users (latest first)</p>

      {/* Filters */}
      <div className="gw-filters">
        <input
          type="text"
          placeholder="Search user or goal..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

        <select value={goal} onChange={(e) => setGoal(e.target.value)}>
          <option value="">All Goals</option>
          <option value="weight loss">Weight Loss</option>
          <option value="muscle gain">Muscle Gain</option>
          <option value="endurance">Endurance</option>
        </select>

        {/* Dates */}
        <div className="gw-date-filters">
          <div className="date-field">
            <label>Start Date</label>
            <input
              type="date"
              value={dateFrom}
              onChange={(e) => setDateFrom(e.target.value)}
            />
          </div>

          <div className="date-field">
            <label>End Date</label>
            <input
              type="date"
              value={dateTo}
              onChange={(e) => setDateTo(e.target.value)}
            />
          </div>

          <button className="date-apply" onClick={applyDateFilter}>
            Apply
          </button>
        </div>

        <button className="filter-reset" onClick={resetFilters}>
          Reset
        </button>
      </div>

      <div className="table-wrap">
        {loading ? (
          <div className="loading">Loading…</div>
        ) : (
          <table className="gw-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>User</th>
                <th>Goal</th>
                <th>Target</th>
                <th>Days</th>
                <th>Duration</th>
                <th>Created</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              {workouts.length === 0 ? (
                <tr>
                  <td colSpan="8" style={{ textAlign: "center" }}>
                    No generated workouts found.
                  </td>
                </tr>
              ) : (
                workouts.map((w) => (
                  <tr key={w.Generate_ID}>
                    <td>{w.Generate_ID}</td>
                    <td>
                      {(
                        w.UserName ??
                        `${w.FirstName || ""} ${w.LastName || ""}`
                      ).trim() || "Unknown"}
                    </td>
                    <td>{w.Goal}</td>
                    <td>{w.Target_Muscle}</td>
                    <td>{w.Workout_Days}</td>
                    <td>{w.Duration_Min ? `${w.Duration_Min} min` : "-"}</td>
                    <td>{w.Created_At}</td>

                    <td className="actions-col">
                      <button className="action view" onClick={() => openView(w.Generate_ID)}>
                        View
                      </button>

                      <button className="action delete" onClick={() => confirmDelete(w.Generate_ID)}>
                        Delete
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      {renderPagination()}

      {viewOpen && selected && (
        <GeneratedWorkoutView
          workout={selected}
          onClose={() => {
            setViewOpen(false);
            setSelected(null);
          }}
        />
      )}

      {confirmOpen && (
        <ConfirmModal
          title="Delete Generated Workout"
          body="Are you sure you want to delete this generated workout? This action cannot be undone."
          onCancel={() => setConfirmOpen(false)}
          onConfirm={doDelete}
        />
      )}

      {dateErrorOpen && (
        <ConfirmModal
          title="Invalid Date Range"
          body="Start date cannot be later than end date."
          hideConfirm={true}
          confirmText="OK"
          onCancel={() => setDateErrorOpen(false)}
        />
      )}
    </div>
  );
}
