import React, { useEffect, useState } from "react";
import axios from "axios";
import "../../styles/admin/GeneratedWorkouts.css";
import GeneratedWorkoutView from "../../components/GeneratedWorkoutView";
import ConfirmModal from "../../components/ConfirmModal";

const API_BASE = "/api";

export default function GeneratedWorkouts() {
  const [workouts, setWorkouts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [viewOpen, setViewOpen] = useState(false);
  const [selected, setSelected] = useState(null);

  // confirm modal state
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [toDelete, setToDelete] = useState(null);

  const load = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API_BASE}/index.php?route=admin&action=getGeneratedWorkouts`);
      if (res.data.success) setWorkouts(res.data.workouts);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const openView = async (id) => {
    try {
      const res = await axios.get(`${API_BASE}/index.php?route=admin&action=getGeneratedWorkoutById&id=${id}`);
      if (res.data.success) {
        setSelected(res.data.workout);
        setViewOpen(true);
      } else {
        alert(res.data.message || "Not found");
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Admin delete (if you have such API) — confirm modal first
  const confirmDelete = (id) => {
    setToDelete(id);
    setConfirmOpen(true);
  };

  const doDelete = async () => {
    if (!toDelete) return;
    try {
      const res = await axios.delete(`${API_BASE}/index.php?route=admin&action=deleteGeneratedWorkout&id=${toDelete}`);
      if (res.data.success) {
        setConfirmOpen(false);
        setToDelete(null);
        load();
      } else {
        alert(res.data.message || "Failed to delete.");
      }
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="admin-page generated-workouts-page">
      <div className="page-header">
        <h2>Generated Workouts</h2>
        <p className="subtitle">All workouts generated by users (latest first)</p>
      </div>

      <div className="table-wrap">
        {loading ? <div className="loading">Loading…</div> : (
          <table className="gw-table">
            <thead>
              <tr>
                <th>#</th>
                <th>User</th>
                <th>Goal</th>
                <th>Target</th>
                <th>Days</th>
                <th>Duration</th>
                <th>Created</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {workouts.length === 0 ? (
                <tr><td colSpan="8" className="empty">No generated workouts yet.</td></tr>
              ) : workouts.map(w => (
                <tr key={w.Generate_ID}>
                  <td>{w.Generate_ID}</td>
                  <td>{ (w.UserName ?? `${w.FirstName || ""} ${w.LastName || ""}`).trim() || "Unknown" }</td>
                  <td>{w.Goal}</td>
                  <td>{w.Target_Muscle}</td>
                  <td>{w.Workout_Days}</td>
                  <td>{w.Duration_Min ? `${w.Duration_Min} min` : "-"}</td>
                  <td>{w.Created_At}</td>
                  <td className="actions-col">
                    <button className="action view" onClick={() => openView(w.Generate_ID)}>View</button>
                    {/* if you have delete endpoint, show delete */}
                    <button className="action delete" onClick={() => confirmDelete(w.Generate_ID)}>Delete</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {viewOpen && selected && (
        <GeneratedWorkoutView workout={selected} onClose={() => { setViewOpen(false); setSelected(null); }} />
      )}

      {confirmOpen && (
        <ConfirmModal
          title="Delete generated workout"
          body="Are you sure you want to delete this generated workout? This action cannot be undone."
          onCancel={() => setConfirmOpen(false)}
          onConfirm={doDelete}
        />
      )}
    </div>
  );
}
